# fly.toml app configuration file generated for jakobot on 2025-02-09T04:21:40-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jakobot'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
